# Generated by Django 3.2.14 on 2022-07-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='credtos',
            new_name='creditos',
        ),
    ]
