# Generated by Django 3.2.14 on 2022-08-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newser', '0004_curso_docente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre', '-creditos'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='newser.docente'),
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
    ]
